# Generated by Django 3.0.14 on 2022-07-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20220704_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
    ]
