# Generated by Django 3.0.14 on 2022-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20220704_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachedPhotoIds',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
