# Generated by Django 3.0.14 on 2022-07-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20220704_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='point',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
